const $=(id)=>document.getElementById(id);
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0);}
function startTheVibe(){window.open("https://music.apple.com/us/search?term=It%20Feels%20So%20Good%20Sonique","_blank");go('home');}
const tripStart=new Date("2026-07-02T07:30:00-05:00").getTime();
function tick(){let diff=tripStart-Date.now();if(diff<0)diff=0;$('days').textContent=Math.floor(diff/86400000);$('hours').textContent=Math.floor((diff%86400000)/3600000);$('minutes').textContent=Math.floor((diff%3600000)/60000);$('seconds').textContent=Math.floor((diff%60000)/1000);}
setInterval(tick,1000);tick();
function bindStoredInputs(){document.querySelectorAll('[data-store]').forEach(el=>{const key='drake-v2-'+el.dataset.store;if(el.type==='checkbox')el.checked=localStorage.getItem(key)==='true';else el.value=localStorage.getItem(key)||'';el.addEventListener('input',()=>{localStorage.setItem(key,el.type==='checkbox'?el.checked:el.value);updatePackingProgress();});el.addEventListener('change',()=>{localStorage.setItem(key,el.type==='checkbox'?el.checked:el.value);updatePackingProgress();});});}
const profileData={myles:{emoji:'🍷',name:'Myles',accent:'myles',title:'Explorer • Creative • Tech • Planner',tasks:['Choose concert outfit','Charge power bank','Pack ID and wallet','Save Trip Anthem','Write first Gold Moment']},lauren:{emoji:'😌',name:'Lauren',accent:'lauren',title:'Style • Calm • Adventure • Vibes',tasks:['Plan Friday look','Pack festival bag','Save Apple Music songs','Add restaurant idea','Write first Gold Moment']}};
function openProfile(who){const p=profileData[who];$('profileContent').innerHTML=`<div class="glass ${p.accent}"><p class="tiny">Profile</p><h2>${p.emoji} ${p.name}</h2><p class="muted">${p.title}</p></div><div class="glass"><h3>${p.name}'s Checklist</h3>${p.tasks.map((t,i)=>`<label><input type="checkbox" data-store="${who}-task-${i}"> ${t}</label>`).join('')}</div><div class="glass"><h3>${p.name}'s Notes</h3><textarea data-store="${who}-notes" placeholder="Personal notes for ${p.name}..."></textarea></div>`;go('profile');bindStoredInputs();}
const packing=[['📄 Essentials',['Festival ticket digital + screenshot saved offline','Government ID','Credit/debit card','Small amount of cash','Health insurance card','Emergency contact information']],['📱 Electronics',['Phone','Charging cable','Power bank','Wall charger','Car charger','Earbuds/headphones','Smartwatch charger if needed']],['👕 Clothing',['Underwear one per day + one extra','Socks one pair per day + one extra','T-shirts/tank tops','Shorts','Lightweight pants','Hoodie or light jacket','Rain jacket/poncho','Sleepwear','Comfortable shoes','Sandals','Hat','Sunglasses']],['🧼 Toiletries',['Toothbrush','Toothpaste','Deodorant','Body wash','Shampoo','Face wash','Razor','Hairbrush/comb','Sunscreen','Lip balm','Toilet paper/travel tissues','Wet wipes','Hand sanitizer']],['💊 Health',['Prescription medications','Pain reliever','Allergy medicine','Bandages','Blister pads','Electrolyte packets','Bug spray']],['🍎 Food & Drinks',['Reusable water bottle','Hydration pack','Snacks','Breakfast items','Coffee/energy drinks','Reusable utensils']],['🎒 Day Pack',['Small backpack or hydration pack','Portable charger','Sunscreen','Hat','Sunglasses','Refillable water bottle','Snacks','Rain poncho','Hand sanitizer','Earplugs']],['🎉 Nice to Have',['Portable fan','Cooling towel','Small blanket','Deck of cards','Camera','Ziplock bags','Duct tape','Carabiners']]];
function renderPacking(){$('packingSections').innerHTML=packing.map((section,si)=>`<details class="pack-section glass" open><summary>${section[0]}</summary>${section[1].map((item,ii)=>`<label><input type="checkbox" data-pack="1" data-store="pack-${si}-${ii}"> ${item}</label>`).join('')}</details>`).join('');}
function updatePackingProgress(){const boxes=[...document.querySelectorAll('[data-pack="1"]')];if(!boxes.length)return;const checked=boxes.filter(b=>b.checked).length;const pct=Math.round((checked/boxes.length)*100);$('packProgress').style.width=pct+'%';$('packStats').textContent=`${checked} of ${boxes.length} packed • ${pct}% complete`;}
const tripDays=['Thursday','Friday','Saturday','Sunday','Monday'];
function renderOutfits(){$('outfitStudio').innerHTML=tripDays.map(day=>`<div class="outfit-card glass"><h3>${day}</h3><input data-store="outfit-${day}-day" placeholder="Day look"><input data-store="outfit-${day}-night" placeholder="Night look"><input data-store="outfit-${day}-shoes" placeholder="Shoes / accessories"><textarea data-store="outfit-${day}-notes" placeholder="Fragrance, hair, backup rain plan..."></textarea></div>`).join('');}
const budgetCats=['Food','Uber / Transit','Shopping','Outfits','Souvenirs','Emergency'];
function renderBudget(){$('budgetRows').innerHTML=budgetCats.map(cat=>`<div class="budget-card glass"><h3>${cat}</h3><input data-store="budget-${cat}-planned" inputmode="decimal" placeholder="Planned budget"><input data-store="budget-${cat}-actual" inputmode="decimal" placeholder="Actual spending"></div>`).join('');}
async function loadWeather(){try{const url="https://api.open-meteo.com/v1/forecast?latitude=29.9511&longitude=-90.0715&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&timezone=America%2FChicago&forecast_days=7";const res=await fetch(url);const data=await res.json();$('weatherList').innerHTML=data.daily.time.map((date,i)=>{const day=new Date(date+"T12:00:00").toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});const high=Math.round(data.daily.temperature_2m_max[i]);const low=Math.round(data.daily.temperature_2m_min[i]);const rain=data.daily.precipitation_probability_max[i];const rec=rain>=40?"Pack the poncho. Bring the fan and cooling towel.":"Light fabrics, sunscreen, and comfortable shoes.";return `<div class="weather-day glass"><h3>${day}</h3><p><b>${high}° / ${low}°</b> • Rain ${rain}%</p><p class="muted">${rec}</p></div>`;}).join('');const firstHigh=Math.round(data.daily.temperature_2m_max[0]);const firstRain=data.daily.precipitation_probability_max[0];$('vibeText').textContent=`New Orleans check: ${firstHigh}° with ${firstRain}% rain chance. Wear breathable clothing, charge your power bank, and keep the mini fan ready.`;}catch(e){$('weatherList').innerHTML=`<div class="glass"><p>Weather loads when online. Backup rule: New Orleans is hot, humid, and afternoon rain loves a cameo.</p></div>`;$('vibeText').textContent="Expect heat, humidity, and possible afternoon storms. Pack light, hydrate, and bring the fan.";}}
function saveGoldMoment(){const title=$('goldTitle').value.trim();const text=$('goldText').value.trim();if(!title&&!text)return;const moments=JSON.parse(localStorage.getItem('drake-v2-gold')||'[]');moments.unshift({title,text,date:new Date().toLocaleString()});localStorage.setItem('drake-v2-gold',JSON.stringify(moments));$('goldTitle').value='';$('goldText').value='';renderGoldMoments();}
function renderGoldMoments(){const moments=JSON.parse(localStorage.getItem('drake-v2-gold')||'[]');$('goldList').innerHTML=moments.map(m=>`<div class="gold-item glass"><p class="tiny">${m.date}</p><h3>${m.title||'Gold Moment'}</h3><p>${m.text}</p></div>`).join('');}
renderPacking();renderOutfits();renderBudget();renderGoldMoments();bindStoredInputs();updatePackingProgress();loadWeather();