const tripStart=new Date("2026-07-02T07:30:00-05:00").getTime();
function tick(){let d=tripStart-Date.now();if(d<0)d=0;days.textContent=Math.floor(d/86400000);hours.textContent=Math.floor(d%86400000/3600000);mins.textContent=Math.floor(d%3600000/60000)}setInterval(tick,1000);tick();
[
"📄 ESSENTIALS",
"Festival ticket (digital & screenshot)",
"Government ID",
"Credit/debit card",
"Cash",
"Health insurance card",
"Emergency contact information",

"📱 ELECTRONICS",
"Phone",
"Charging cable",
"Power bank",
"Wall charger",
"Car charger",
"Earbuds",
"Smartwatch charger",

"👕 CLOTHING",
"Underwear",
"Socks",
"T-shirts",
"Shorts",
"Lightweight pants",
"Hoodie or light jacket",
"Rain jacket / Poncho",
"Sleepwear",
"Comfortable shoes",
"Sandals",
"Hat",
"Sunglasses",

"🧼 TOILETRIES",
"Toothbrush",
"Toothpaste",
"Deodorant",
"Body wash",
"Shampoo",
"Face wash",
"Razor",
"Hairbrush / Comb",
"Sunscreen",
"Lip balm",
"Wet wipes",
"Hand sanitizer",

"💊 HEALTH",
"Prescription medications",
"Pain reliever",
"Allergy medicine",
"Bandages",
"Blister pads",
"Electrolyte packets",
"Bug spray",

"🎒 FESTIVAL BAG",
"Clear bag",
"Portable charger",
"Portable fan",
"Cooling towel",
"Sunscreen",
"Sunglasses",
"Refillable water bottle",
"Snacks",
"Rain poncho",
"Hand sanitizer",
"Earplugs",

"🍎 HOTEL SNACKS",
"Water",
"Breakfast items",
"Coffee",
"Energy drinks",

"🎉 NICE TO HAVE",
"Camera",
"Ziplock bags",
"Deck of cards",
"Carabiners"
]
packingList.innerHTML=items.map((x,i)=>`<label><input type="checkbox" data-k="p${i}"> ${x}</label>`).join("");
document.querySelectorAll("input[type=checkbox]").forEach(c=>{c.checked=localStorage[c.dataset.k]==="true";c.onchange=()=>localStorage[c.dataset.k]=c.checked});
async function weather(){try{let r=await fetch("https://api.open-meteo.com/v1/forecast?latitude=29.9511&longitude=-90.0715&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&timezone=America%2FChicago&forecast_days=5");let j=await r.json();weatherBox.innerHTML=j.daily.time.map((t,i)=>`<p><b>${new Date(t+"T12:00").toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</b><br>${Math.round(j.daily.temperature_2m_max[i])}° / ${Math.round(j.daily.temperature_2m_min[i])}° • Rain ${j.daily.precipitation_probability_max[i]}%</p>`).join("")}catch(e){weatherBox.textContent="Weather loads when online. Expect heat, humidity, and possible afternoon storms."}}weather();
